#include "pod_particle_finite_strain.h"
namespace mpm {
namespace pod {
namespace particlefinitestrain {
const size_t dst_offset[NFIELDS] = {
    // Solid phase
    HOFFSET(PODParticleFiniteStrain, id),
    HOFFSET(PODParticleFiniteStrain, mass),
    HOFFSET(PODParticleFiniteStrain, volume),
    HOFFSET(PODParticleFiniteStrain, pressure),
    HOFFSET(PODParticleFiniteStrain, coord_x),
    HOFFSET(PODParticleFiniteStrain, coord_y),
    HOFFSET(PODParticleFiniteStrain, coord_z),
    HOFFSET(PODParticleFiniteStrain, displacement_x),
    HOFFSET(PODParticleFiniteStrain, displacement_y),
    HOFFSET(PODParticleFiniteStrain, displacement_z),
    HOFFSET(PODParticleFiniteStrain, nsize_x),
    HOFFSET(PODParticleFiniteStrain, nsize_y),
    HOFFSET(PODParticleFiniteStrain, nsize_z),
    HOFFSET(PODParticleFiniteStrain, velocity_x),
    HOFFSET(PODParticleFiniteStrain, velocity_y),
    HOFFSET(PODParticleFiniteStrain, velocity_z),
    HOFFSET(PODParticleFiniteStrain, acceleration_x),
    HOFFSET(PODParticleFiniteStrain, acceleration_y),
    HOFFSET(PODParticleFiniteStrain, acceleration_z),
    HOFFSET(PODParticleFiniteStrain, stress_xx),
    HOFFSET(PODParticleFiniteStrain, stress_yy),
    HOFFSET(PODParticleFiniteStrain, stress_zz),
    HOFFSET(PODParticleFiniteStrain, tau_xy),
    HOFFSET(PODParticleFiniteStrain, tau_yz),
    HOFFSET(PODParticleFiniteStrain, tau_xz),
    HOFFSET(PODParticleFiniteStrain, strain_xx),
    HOFFSET(PODParticleFiniteStrain, strain_yy),
    HOFFSET(PODParticleFiniteStrain, strain_zz),
    HOFFSET(PODParticleFiniteStrain, gamma_xy),
    HOFFSET(PODParticleFiniteStrain, gamma_yz),
    HOFFSET(PODParticleFiniteStrain, gamma_xz),
    HOFFSET(PODParticleFiniteStrain, epsilon_v),
    HOFFSET(PODParticleFiniteStrain, status),
    HOFFSET(PODParticleFiniteStrain, cell_id),
    HOFFSET(PODParticleFiniteStrain, material_id),
    HOFFSET(PODParticleFiniteStrain, nstate_vars),
    HOFFSET(PODParticleFiniteStrain, svars[0]),
    HOFFSET(PODParticleFiniteStrain, svars[1]),
    HOFFSET(PODParticleFiniteStrain, svars[2]),
    HOFFSET(PODParticleFiniteStrain, svars[3]),
    HOFFSET(PODParticleFiniteStrain, svars[4]),
    HOFFSET(PODParticleFiniteStrain, svars[5]),
    HOFFSET(PODParticleFiniteStrain, svars[6]),
    HOFFSET(PODParticleFiniteStrain, svars[7]),
    HOFFSET(PODParticleFiniteStrain, svars[8]),
    HOFFSET(PODParticleFiniteStrain, svars[9]),
    HOFFSET(PODParticleFiniteStrain, svars[10]),
    HOFFSET(PODParticleFiniteStrain, svars[11]),
    HOFFSET(PODParticleFiniteStrain, svars[12]),
    HOFFSET(PODParticleFiniteStrain, svars[13]),
    HOFFSET(PODParticleFiniteStrain, svars[14]),
    HOFFSET(PODParticleFiniteStrain, svars[15]),
    HOFFSET(PODParticleFiniteStrain, svars[16]),
    HOFFSET(PODParticleFiniteStrain, svars[17]),
    HOFFSET(PODParticleFiniteStrain, svars[18]),
    HOFFSET(PODParticleFiniteStrain, svars[19]),
    // Finite strain
    HOFFSET(PODParticleFiniteStrain, defgrad_11),
    HOFFSET(PODParticleFiniteStrain, defgrad_12),
    HOFFSET(PODParticleFiniteStrain, defgrad_13),
    HOFFSET(PODParticleFiniteStrain, defgrad_21),
    HOFFSET(PODParticleFiniteStrain, defgrad_22),
    HOFFSET(PODParticleFiniteStrain, defgrad_23),
    HOFFSET(PODParticleFiniteStrain, defgrad_31),
    HOFFSET(PODParticleFiniteStrain, defgrad_32),
    HOFFSET(PODParticleFiniteStrain, defgrad_33),
};

// Get size of particletwophase
PODParticleFiniteStrain particle;
const size_t dst_sizes[NFIELDS] = {
    // Solid phase
    sizeof(particle.id),
    sizeof(particle.mass),
    sizeof(particle.volume),
    sizeof(particle.pressure),
    sizeof(particle.coord_x),
    sizeof(particle.coord_y),
    sizeof(particle.coord_z),
    sizeof(particle.displacement_x),
    sizeof(particle.displacement_y),
    sizeof(particle.displacement_z),
    sizeof(particle.nsize_x),
    sizeof(particle.nsize_y),
    sizeof(particle.nsize_z),
    sizeof(particle.velocity_x),
    sizeof(particle.velocity_y),
    sizeof(particle.velocity_z),
    sizeof(particle.acceleration_x),
    sizeof(particle.acceleration_y),
    sizeof(particle.acceleration_z),
    sizeof(particle.stress_xx),
    sizeof(particle.stress_yy),
    sizeof(particle.stress_zz),
    sizeof(particle.tau_xy),
    sizeof(particle.tau_yz),
    sizeof(particle.tau_xz),
    sizeof(particle.strain_xx),
    sizeof(particle.strain_yy),
    sizeof(particle.strain_zz),
    sizeof(particle.gamma_xy),
    sizeof(particle.gamma_yz),
    sizeof(particle.gamma_xz),
    sizeof(particle.epsilon_v),
    sizeof(particle.status),
    sizeof(particle.cell_id),
    sizeof(particle.material_id),
    sizeof(particle.nstate_vars),
    sizeof(particle.svars[0]),
    sizeof(particle.svars[1]),
    sizeof(particle.svars[2]),
    sizeof(particle.svars[3]),
    sizeof(particle.svars[4]),
    sizeof(particle.svars[5]),
    sizeof(particle.svars[6]),
    sizeof(particle.svars[7]),
    sizeof(particle.svars[8]),
    sizeof(particle.svars[9]),
    sizeof(particle.svars[10]),
    sizeof(particle.svars[11]),
    sizeof(particle.svars[12]),
    sizeof(particle.svars[13]),
    sizeof(particle.svars[14]),
    sizeof(particle.svars[15]),
    sizeof(particle.svars[16]),
    sizeof(particle.svars[17]),
    sizeof(particle.svars[18]),
    sizeof(particle.svars[19]),
    // Finite strain
    sizeof(particle.defgrad_11),
    sizeof(particle.defgrad_12),
    sizeof(particle.defgrad_13),
    sizeof(particle.defgrad_21),
    sizeof(particle.defgrad_22),
    sizeof(particle.defgrad_23),
    sizeof(particle.defgrad_31),
    sizeof(particle.defgrad_32),
    sizeof(particle.defgrad_33),
};

// Define particletwophase field information
const char* field_names[NFIELDS] = {
    // Solid phase
    "id",
    "mass",
    "volume",
    "pressure",
    "coord_x",
    "coord_y",
    "coord_z",
    "displacement_x",
    "displacement_y",
    "displacement_z",
    "nsize_x",
    "nsize_y",
    "nsize_z",
    "velocity_x",
    "velocity_y",
    "velocity_z",
    "acceleration_x",
    "acceleration_y",
    "acceleration_z",
    "stress_xx",
    "stress_yy",
    "stress_zz",
    "tau_xy",
    "tau_yz",
    "tau_xz",
    "strain_xx",
    "strain_yy",
    "strain_zz",
    "gamma_xy",
    "gamma_yz",
    "gamma_xz",
    "epsilon_v",
    "status",
    "cell_id",
    "material_id",
    "nstate_vars",
    "svars_0",
    "svars_1",
    "svars_2",
    "svars_3",
    "svars_4",
    "svars_5",
    "svars_6",
    "svars_7",
    "svars_8",
    "svars_9",
    "svars_10",
    "svars_11",
    "svars_12",
    "svars_13",
    "svars_14",
    "svars_15",
    "svars_16",
    "svars_17",
    "svars_18",
    "svars_19",
    // Finite strain
    "defgrad_11",
    "defgrad_12",
    "defgrad_13",
    "defgrad_21",
    "defgrad_22",
    "defgrad_23",
    "defgrad_31",
    "defgrad_32",
    "defgrad_33",
};

// Initialize field types
const hid_t field_type[NFIELDS] = {
    H5T_NATIVE_LLONG,  H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_HBOOL,  H5T_NATIVE_LLONG,  H5T_NATIVE_UINT,   H5T_NATIVE_UINT,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE};
}  // namespace particlefinitestrain
}  // namespace pod
}  // namespace mpm
