#include "pod_particle_xmpm.h"
namespace mpm {
namespace pod {
namespace particlexmpm {
const size_t dst_offset[NFIELDS] = {
    // Solid phase
    HOFFSET(PODParticleXMPM, id),
    HOFFSET(PODParticleXMPM, mass),
    HOFFSET(PODParticleXMPM, volume),
    HOFFSET(PODParticleXMPM, pressure),
    HOFFSET(PODParticleXMPM, coord_x),
    HOFFSET(PODParticleXMPM, coord_y),
    HOFFSET(PODParticleXMPM, coord_z),
    HOFFSET(PODParticleXMPM, displacement_x),
    HOFFSET(PODParticleXMPM, displacement_y),
    HOFFSET(PODParticleXMPM, displacement_z),
    HOFFSET(PODParticleXMPM, nsize_x),
    HOFFSET(PODParticleXMPM, nsize_y),
    HOFFSET(PODParticleXMPM, nsize_z),
    HOFFSET(PODParticleXMPM, velocity_x),
    HOFFSET(PODParticleXMPM, velocity_y),
    HOFFSET(PODParticleXMPM, velocity_z),
    HOFFSET(PODParticleXMPM, acceleration_x),
    HOFFSET(PODParticleXMPM, acceleration_y),
    HOFFSET(PODParticleXMPM, acceleration_z),
    HOFFSET(PODParticleXMPM, stress_xx),
    HOFFSET(PODParticleXMPM, stress_yy),
    HOFFSET(PODParticleXMPM, stress_zz),
    HOFFSET(PODParticleXMPM, tau_xy),
    HOFFSET(PODParticleXMPM, tau_yz),
    HOFFSET(PODParticleXMPM, tau_xz),
    HOFFSET(PODParticleXMPM, strain_xx),
    HOFFSET(PODParticleXMPM, strain_yy),
    HOFFSET(PODParticleXMPM, strain_zz),
    HOFFSET(PODParticleXMPM, gamma_xy),
    HOFFSET(PODParticleXMPM, gamma_yz),
    HOFFSET(PODParticleXMPM, gamma_xz),
    HOFFSET(PODParticleXMPM, defgrad_00),
    HOFFSET(PODParticleXMPM, defgrad_01),
    HOFFSET(PODParticleXMPM, defgrad_02),
    HOFFSET(PODParticleXMPM, defgrad_10),
    HOFFSET(PODParticleXMPM, defgrad_11),
    HOFFSET(PODParticleXMPM, defgrad_12),
    HOFFSET(PODParticleXMPM, defgrad_20),
    HOFFSET(PODParticleXMPM, defgrad_21),
    HOFFSET(PODParticleXMPM, defgrad_22),
    HOFFSET(PODParticleXMPM, status),
    HOFFSET(PODParticleXMPM, cell_id),
    HOFFSET(PODParticleXMPM, material_id),
    HOFFSET(PODParticleXMPM, nstate_vars),
    HOFFSET(PODParticleXMPM, svars[0]),
    HOFFSET(PODParticleXMPM, svars[1]),
    HOFFSET(PODParticleXMPM, svars[2]),
    HOFFSET(PODParticleXMPM, svars[3]),
    HOFFSET(PODParticleXMPM, svars[4]),
    HOFFSET(PODParticleXMPM, svars[5]),
    HOFFSET(PODParticleXMPM, svars[6]),
    HOFFSET(PODParticleXMPM, svars[7]),
    HOFFSET(PODParticleXMPM, svars[8]),
    HOFFSET(PODParticleXMPM, svars[9]),
    HOFFSET(PODParticleXMPM, svars[10]),
    HOFFSET(PODParticleXMPM, svars[11]),
    HOFFSET(PODParticleXMPM, svars[12]),
    HOFFSET(PODParticleXMPM, svars[13]),
    HOFFSET(PODParticleXMPM, svars[14]),
    HOFFSET(PODParticleXMPM, svars[15]),
    HOFFSET(PODParticleXMPM, svars[16]),
    HOFFSET(PODParticleXMPM, svars[17]),
    HOFFSET(PODParticleXMPM, svars[18]),
    HOFFSET(PODParticleXMPM, svars[19]),
    // 64
    // XMPM variables
    HOFFSET(PODParticleXMPM, levelset_phi),
};

// Get size of particleXMPM
PODParticleXMPM particle;
const size_t dst_sizes[NFIELDS] = {
    sizeof(particle.id),
    sizeof(particle.mass),
    sizeof(particle.volume),
    sizeof(particle.pressure),
    sizeof(particle.coord_x),
    sizeof(particle.coord_y),
    sizeof(particle.coord_z),
    sizeof(particle.displacement_x),
    sizeof(particle.displacement_y),
    sizeof(particle.displacement_z),
    sizeof(particle.nsize_x),
    sizeof(particle.nsize_y),
    sizeof(particle.nsize_z),
    sizeof(particle.velocity_x),
    sizeof(particle.velocity_y),
    sizeof(particle.velocity_z),
    sizeof(particle.acceleration_x),
    sizeof(particle.acceleration_y),
    sizeof(particle.acceleration_z),
    sizeof(particle.stress_xx),
    sizeof(particle.stress_yy),
    sizeof(particle.stress_zz),
    sizeof(particle.tau_xy),
    sizeof(particle.tau_yz),
    sizeof(particle.tau_xz),
    sizeof(particle.strain_xx),
    sizeof(particle.strain_yy),
    sizeof(particle.strain_zz),
    sizeof(particle.gamma_xy),
    sizeof(particle.gamma_yz),
    sizeof(particle.gamma_xz),
    sizeof(particle.defgrad_00),
    sizeof(particle.defgrad_01),
    sizeof(particle.defgrad_02),
    sizeof(particle.defgrad_10),
    sizeof(particle.defgrad_11),
    sizeof(particle.defgrad_12),
    sizeof(particle.defgrad_20),
    sizeof(particle.defgrad_21),
    sizeof(particle.defgrad_22),
    sizeof(particle.status),
    sizeof(particle.cell_id),
    sizeof(particle.material_id),
    sizeof(particle.nstate_vars),
    sizeof(particle.svars[0]),
    sizeof(particle.svars[1]),
    sizeof(particle.svars[2]),
    sizeof(particle.svars[3]),
    sizeof(particle.svars[4]),
    sizeof(particle.svars[5]),
    sizeof(particle.svars[6]),
    sizeof(particle.svars[7]),
    sizeof(particle.svars[8]),
    sizeof(particle.svars[9]),
    sizeof(particle.svars[10]),
    sizeof(particle.svars[11]),
    sizeof(particle.svars[12]),
    sizeof(particle.svars[13]),
    sizeof(particle.svars[14]),
    sizeof(particle.svars[15]),
    sizeof(particle.svars[16]),
    sizeof(particle.svars[17]),
    sizeof(particle.svars[18]),
    sizeof(particle.svars[19]),
    // XMPM
    sizeof(particle.levelset_phi),

};

// Define particlexmpm information
const char* field_names[NFIELDS] = {
    // Solid phase
    "id",
    "mass",
    "volume",
    "pressure",
    "coord_x",
    "coord_y",
    "coord_z",
    "displacement_x",
    "displacement_y",
    "displacement_z",
    "nsize_x",
    "nsize_y",
    "nsize_z",
    "velocity_x",
    "velocity_y",
    "velocity_z",
    "acceleration_x",
    "acceleration_y",
    "acceleration_z",
    "stress_xx",
    "stress_yy",
    "stress_zz",
    "tau_xy",
    "tau_yz",
    "tau_xz",
    "strain_xx",
    "strain_yy",
    "strain_zz",
    "gamma_xy",
    "gamma_yz",
    "gamma_xz",
    "defgrad_00",
    "defgrad_01",
    "defgrad_02",
    "defgrad_10",
    "defgrad_11",
    "defgrad_12",
    "defgrad_20",
    "defgrad_21",
    "defgrad_22",
    "status",
    "cell_id",
    "material_id",
    "nstate_vars",
    "svars_0",
    "svars_1",
    "svars_2",
    "svars_3",
    "svars_4",
    "svars_5",
    "svars_6",
    "svars_7",
    "svars_8",
    "svars_9",
    "svars_10",
    "svars_11",
    "svars_12",
    "svars_13",
    "svars_14",
    "svars_15",
    "svars_16",
    "svars_17",
    "svars_18",
    "svars_19",
    // XMPM
    "levelset_phi",
};

// Initialize field types
const hid_t field_type[NFIELDS] = {
    H5T_NATIVE_LLONG, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_HBOOL, H5T_NATIVE_LLONG, H5T_NATIVE_UINT, H5T_NATIVE_UINT,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE, H5T_NATIVE_DOUBLE,
    // 64
    // XMPM
    H5T_NATIVE_DOUBLE};  // namespace particlexmpm
}  // namespace particlexmpm
}  // namespace pod
}  // namespace mpm
